
 

version: "3.7"
services: 
  nginx:
    image: nginx:1.15-alpine
    restart: always
    ports:
      - 8002:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web1_net
      - web2_net 
      
networks:
    web1_net:
        external: true
    web2_net:
        external: true
    

