version: "3"

services:
    web1:
        build:
            context: ./django1/
        # command: python manage.py runserver 0.0.0.0:8000
        command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ./django1/:/usr/src/app/
            - static_files:/usr/src/app/staticfiles
        expose:
            - 8000
        # ports:
        #   - 8000:8000
        # env_file:
        #     - ./.env/dev.env
    web2:
        build:
            context: ./django2/
        # command: python manage.py runserver 0.0.0.0:8000
        command: gunicorn demo.wsgi:application --bind 0.0.0.0:8080
        volumes:
            - ./django2/:/usr/src/app/
            - static_files:/usr/src/app/staticfiles
        expose:
            - 8080
        # ports:
        #   - 8000:8000
        # env_file:
        #     - ./.env/dev.env
    client:
        build:
            context: ./nginx/
        ports:
            - 80:80
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - static_files:/home/app/staticfiles

volumes:
  static_files: