version: "3"

services:
    client:
        build:
            context: ./nginx/
        ports:
            - 8001:80
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./log/:/var/log/nginx/
            - ./nginx/html/:/usr/share/nginx/html/

