version: "3"

services:
    client:
        build:
            context: ./nginx/
        ports:
            - 80:80
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/html/:/usr/share/nginx/html/
